---
title: "Data Resphaping: Exercise"
author: "Bert"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    code_folding: show
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T, warning = F, message = F)
```

# Data Preparation

- Load the package "tidyverse".

```{r}
suppressPackageStartupMessages(library(tidyr))
```

- Load the data "population".

- Inspect it by loading the first observations of this data.

```{r}
data("population")
population %>%
  head(1)
```

# Data Reshaping

- The data is shaped in a tidy format. Please change it to a wide format (rows represent countries, columns represent years, values represent population).

```{r}
population_wide <- population %>%
  spread(key = "year", value = "population")
```

- Now take the wide data and reshape it back to a tidy format. 

```{r}
population_tidy <- population_wide %>%
  gather(key = "year", value = "population", 2:ncol(.)) # ncol(.) is the position of last column
population_tidy
```


